CREATE TABLE ECO_USER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    ROLE_ID INT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    PHONE VARCHAR(50),
    NATIONALITY VARCHAR(100),
    GENDER VARCHAR(10),
    REGISTRATION_DATE DATETIME,
    BIRTHDAY DATETIME
);

CREATE TABLE ECO_ROLE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_DESC VARCHAR(255) NOT NULL
);

CREATE TABLE ECO_PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL,
    STOCK_QUANTITY INT,
    COLOR VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    CREATION_DATE DATETIME
);

CREATE TABLE ECO_ORDERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ORDER_NUMBER VARCHAR(255) NOT NULL,
    TRANSACTION_DATE DATETIME NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES ECO_USER(ID)
);

CREATE TABLE ECO_ORDER_DETAILS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ECO_ORDERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES ECO_PRODUCT(ID)
);

CREATE VIEW ECO_VW_ORDER_DETAILS AS
SELECT
    OD.ID AS ID,
    O.ID AS ORDER_ID,
    O.USER_ID AS USER_ID,
    OD.QUANTITY AS PRODUCT_QUANTITY,
    (OD.QUANTITY * P.PRICE) AS TOTAL_PRICE,
    P.ID AS PRODUCT_ID,
    U.FIRST_NAME AS CUSTOMER_NAME,
    U.ADDRESS AS CUSTOMER_ADDRESS,
    U.PHONE AS CUSTOMER_PHONE,
    O.ORDER_NUMBER AS ORDER_NUMBER,
    P.STOCK_QUANTITY AS STOCK_QUANTITY,
    P.COLOR AS PRODUCT_COLOR,
    P.DESCRIPTION AS PRODUCT_DESCRIPTION,
    P.PRODUCT_NAME AS PRODUCT_NAME,
    O.TRANSACTION_DATE AS TRANSACTION_DATE
FROM 
    ECO_ORDERS O
JOIN 
    ECO_ORDER_DETAILS OD ON O.ID = OD.ORDER_ID
JOIN 
    ECO_USER U ON O.USER_ID = U.ID
JOIN 
    ECO_PRODUCT P ON OD.PRODUCT_ID = P.ID;
    
    
CREATE SEQUENCE ECO_INSTANCES_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOCYCLE;

CREATE SEQUENCE ECO_ORDERS_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 21 
    CACHE 20 
    NOCYCLE;

CREATE SEQUENCE ECO_ORDER_DETAILS_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOCYCLE;

CREATE SEQUENCE ECO_PROCESSES_GROUPS_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOCYCLE;

CREATE SEQUENCE ECO_PROCESSES_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOCYCLE;

CREATE SEQUENCE ECO_PRODUCT_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 21 
    CACHE 20 
    NOCYCLE;

CREATE SEQUENCE ECO_PRODUCT_TRANSACTION_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOCYCLE;

CREATE SEQUENCE ECO_ROLE_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOCYCLE;

CREATE SEQUENCE ECO_TASKS_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 1 
    CACHE 20 
    NOCYCLE;

CREATE SEQUENCE ECO_USER_SEQ 
    MINVALUE 1 
    MAXVALUE 999999999 
    INCREMENT BY 1 
    START WITH 22 
    CACHE 20 
    NOCYCLE;
